[project]
name = "chatapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.2.0",
    "langchain>=0.3.18",
    "langchain-groq>=0.2.4",
    "langgraph>=0.2.73",
]
